---
- name: Create EBS application
  shell: eb init {{ ebs_app_name }} -r {{ ebs_region }} -p docker -k krisztian_lachata_aws

- name: Create EBS environments
  shell: eb create {{ item.name }} -r {{ ebs_region }} -c {{ item.cname }} -t web -p docker -s --sample -k krisztian_lachata_aws --tags app={{ ebs_app_name }}
  with_items:
     - { name: 'deliverypipeline-node-1', cname: 'deliverypipeline-prod' }
     - { name: 'deliverypipeline-node-2', cname: 'deliverypipeline-staging' }
