---
- name: Update nodes
  yum: name=* state=latest

- name: Assures /app dir exists
  file: path=/app state=directory

- name: Copy application.conf
  template: src=application.conf dest=/app/application.conf

- name: Copy logback.xml
  template: src=logback.xml dest=/app/logback.xml